
DROP TABLE GUI_LOTES 

CREATE TABLE GUI_LOTES AS
SELECT B.ID_LOTE, 
       REF_EXT FILE_ID, 
       C.CODIGOLINEA LINEA, 
       A.CODIGOTRAYECTO RAMAL
FROM EXP_movimientotarjeta A, LOTE B, LINEA C
WHERE FECHATRX > TO_DATE('20140802','YYYYMMDD') AND FECHATRX < TO_DATE('20140803','YYYYMMDD')
  AND FECHAINGRESO > TO_DATE('20140801','YYYYMMDD') AND FECHAINGRESO < TO_DATE('20140905','YYYYMMDD')  
  AND A.CODIGOLINEA = C.IDLINEA 
  AND A.idarchivointercambio = B.id_lote
  AND AREAGEOGRAFICA IN (1,11,12,13)
GROUP BY B.ID_LOTE, REF_EXT, C.CODIGOLINEA, A.CODIGOTRAYECTO;

commit


CREATE TABLE RAWPTOCONTROL
(
  LINEA            VARCHAR(50),
  RAMAL            VARCHAR(5),
  FILE_ID          REAL                       NOT NULL,
  C_CONTROL_POINT  REAL,
  LONGITUD         REAL,
  LATITUD          REAL,
  FECHAPTO         DATE,
  ESTADO           CHAR(1),
  DIFSEC           REAL,
  SEGUNDOSPTO      REAL,
  FECHAINGRESO     DATE
);

DROP TABLE RAWPTOCONTROL

/* Formatted on 08/04/2015 03:16:53 p.m. (QP5 v5.256.13226.35538) */
CREATE TABLE RAWPTOCONTROL
AS
     SELECT B.LINEA,
            B.RAMAL,
            P.FILE_ID,
            C_CONTROL_POINT,
            LONGITUDE LONGITUD,
            LATITUDE LATITUD,
            DATE_TIME FECHAPTO,
            'S' estado,
            (CASE WHEN LAG(P.file_id, 1) OVER (ORDER BY P.FILE_ID, P.C_CONTROL_POINT) =
                        P.file_id  THEN  DATE_TIME - LAG(DATE_TIME, 1) OVER (ORDER BY P.FILE_ID, P.C_CONTROL_POINT)
             END) * 24*60*60
               DIFSEC,
            (DATE_TIME- TO_DATE('20000101','YYYYMMDD')) * 24 * 60 * 60 SEGUNDOSPTO
       FROM USR_POSICIONAMIENTO.TRX_POSITIONING P, GUI_LOTES B
      WHERE P.FILE_ID = B.FILE_ID
   ORDER BY FILE_ID, C_CONTROL_POINT;
   
   
   COMMIT;
   
   UPDATE RAWPTOCONTROL
   SET ESTADO = CASE WHEN DIFSEC > 235 AND DIFSEC < 245 THEN 'S' ELSE 'N' END;
   
   COMMIT;

    
   SELECT * FROM RAWPTOCONTROL WHERE FILE_ID = 22839787

   SELECT * FROM USR_POSICIONAMIENTO.TRX_POSITIONING WHERE FILE_ID = 22839787
   
   SELECT * FROM GUI_LOTES WHERE FILE_ID = 22839787
    

