CREATE TABLE USRNSSA.THE_RAMALES
(
  LINEA           VARCHAR2(50 BYTE),
  RAMAL           VARCHAR2(5 BYTE),
  DESCRIPCION     VARCHAR2(35 BYTE)             NOT NULL,
  ID_EMPRESA      NUMBER(10),
  CODIGOLINEA     NUMBER(10),
  AREAGEOGRAFICA  NUMBER(2),
  CANTIDAD_TRX    NUMBER
)


CREATE TABLE USRNSSA.THE_LOTES
(
  CODIGOENTIDAD         NUMBER(10),
  CODIGOLINEA           NUMBER(10),
  RAMAL                 VARCHAR2(5 BYTE),
  IDARCHIVOINTERCAMBIO  INTEGER,
  FILE_ID               NUMBER(10),
  CANTIDAD_TRX          NUMBER,
  MINFECHAINGRESO       DATE,
  MAXFECHAINGRESO       DATE,
  SELECTTED             VARCHAR2(1 BYTE)
)

CREATE INDEX the_lotes_IDX1 ON the_lotes (IDARCHIVOINTERCAMBIO) TABLESPACE USRNSSA_IDX 


CREATE TABLE USRNSSA.PTOCONTROL201505
(
  CODIGOLINEA      NUMBER(10),
  RAMAL            VARCHAR2(5 BYTE),
  FILE_ID          NUMBER                       NOT NULL,
  C_CONTROL_POINT  NUMBER,
  LONGITUD         NUMBER(22,9),
  LATITUD          NUMBER(22,9),
  FECHAPTO         DATE,
  ESTADO           CHAR(1 BYTE),
  DIFSEC           NUMBER,
  SEGUNDOSPTO      NUMBER,
  MINFECHAINGRESO  DATE
);