python inicio.py -sign_ag 41
python inicio.py -sign_ag 70
python inicio.py -sign_ag 145
python inicio.py -sign_ag 159
python inicio.py -sign_ag 182
python inicio.py -sign_ag 138
python inicio.py -sign_ag 142
python inicio.py -sign_ag 150
python inicio.py -sign_ag 151
python inicio.py -sign_ag 42
python inicio.py -sign_ag 53
python inicio.py -sign_ag 66
python inicio.py -sign_ag 71
python inicio.py -sign_ag 87
python inicio.py -sign_ag 101
python inicio.py -sign_ag 119
python inicio.py -sign_ag 147
python inicio.py -sign_ag 190
python inicio.py -sign_ag 191
python inicio.py -sign_ag 265
python inicio.py -sign_ag 619
python inicio.py -sign_ag 85
python inicio.py -sign_ag 100
python inicio.py -sign_ag 106
python inicio.py -sign_ag 110
python inicio.py -sign_ag 123
python inicio.py -sign_ag 127
python inicio.py -sign_ag 130
python inicio.py -sign_ag 141
python inicio.py -sign_ag 154
python inicio.py -sign_ag 156
python inicio.py -sign_ag 170
python inicio.py -sign_ag 179
python inicio.py -sign_ag 180
python inicio.py -sign_ag 184
python inicio.py -sign_ag 257
python inicio.py -sign_ag 330
python inicio.py -sign_ag 43
python inicio.py -sign_ag 63
python inicio.py -sign_ag 103
python inicio.py -sign_ag 133
python inicio.py -sign_ag 153
python inicio.py -sign_ag 155
python inicio.py -sign_ag 165
python inicio.py -sign_ag 172
python inicio.py -sign_ag 193
python inicio.py -sign_ag 385
python inicio.py -sign_ag 35
python inicio.py -sign_ag 55
python inicio.py -sign_ag 67
python inicio.py -sign_ag 76
python inicio.py -sign_ag 79
python inicio.py -sign_ag 143
python inicio.py -sign_ag 278
python inicio.py -sign_ag 50
python inicio.py -sign_ag 57
python inicio.py -sign_ag 107
python inicio.py -sign_ag 220
python inicio.py -sign_ag 224
python inicio.py -sign_ag 310
python inicio.py -sign_ag 315
