
SELECT LINEA, RAMAL, SENTIDO, CAST(SUBSTR(PUNTO,7,11) AS NUMBER) LONGITUD, CAST(SUBSTR(PUNTO,17,11) AS NUMBER) LATITUD, MILEPOST FROM ESQUINASLINEAS WHERE LINEA = 118 ORDER BY MILEPOST

AND RAMAL = ORDER BY MILEPOST

ALTER TABLE PTOSCONTROL
 COLUMN LINEA NUMBER

SELECT LINEA, RAMAL, IDARCHIVOINTERCAMBIO, CONTROL_POINT_1, LONGITUDPTO1, LATITUDPTO1, FECHAPTO1 FROM PTOSCONTROL ORDER BY CONTROL_POINT_1;



DROP TABLE PTOSCONTROL2;

CREATE TABLE PTOSCONTROL2(
  linea INTEGER,
  ramal INTEGER,
  idarchivointercambio INTEGER,
  control_point_1 INTEGER,
  longitudpto1 REAL,
  latitudpto1 REAL,
  fechapto1 TEXT,
  segundosPto1 real
);
 
commit;

INSERT INTO PTOSCONTROL2
SELECT LINEA, RAMAL, IDARCHIVOINTERCAMBIO, CONTROL_POINT_1, LONGITUDPTO1, LATITUDPTO1, FECHAPTO1, strftime('%s', FECHAPTO1) segundosPto1
FROM PTOSCONTROL ORDER BY CONTROL_POINT_1;

COMMIT;

SELECT * FROM PTOSCONTROL2 ORDER BY CONTROL_POINT_1;
