CREATE TABLE THE_LOTES
(
  CODIGOENTIDAD         numeric,
  CODIGOLINEA           numeric,
  RAMAL                 character varying(5),
  IDARCHIVOINTERCAMBIO  int,
  FILE_ID               numeric,
  CANTIDAD_TRX          numeric,
  MINFECHAINGRESO       DATE,
  MAXFECHAINGRESO       DATE,
  SELECTTED             character varying(1)
);

SET datestyle = "ISO, DMY";

--TRUNCATE TABLE THE_LOTES;

COPY THE_LOTES FROM 'E:\pruebas\THE_LOTES.CSV' CSV  DELIMITER ';'  HEADER;

select * from the_lotes
WHERE SELECTTED IS NOT NULL;

ALTER TABLE THE_LOTES
ADD PROCESADO character varying(2);

--SE MARCAN LOS LETES CON 2 CUANDO SE SUMARON LA SEGUNDA CAMANDA DE PUNTOS DE CONTROL
UPDATE THE_LOTES
SET SELECTTED = '2'
WHERE FILE_ID IN (SELECT DISTINCT FILE_ID FROM PTOCONTROL201505 WHERE CAMADA = 2)
  AND SELECTTED IS NULL;

--SE MARCAN CON D LOS REGISTROS DE LOTES QUE SON DEFINITIVOS Y SE VAN A USAR PARA EL CALCULO DEL DESTINO
UPDATE THE_LOTES
SET SELECTTED = 'D'
WHERE FILE_ID IN (SELECT DISTINCT FILE_ID FROM THE_VIAJESMAYO)
  AND SELECTTED = 'P';
--19743

SELECT SELECTTED, PROCESADO, COUNT(*)
FROM THE_LOTES
GROUP BY SELECTTED, PROCESADO
ORDER BY SELECTTED, PROCESADO;

UPDATE THE_LOTES SET SELECTTED = 'D'
WHERE IDARCHIVOINTERCAMBIO IN (SELECT DISTINCT IDARCHIVOINTERCAMBIO FROM THE_VIAJESMAYO)
  AND SELECTTED IS NULL;
  
---marco nuevos lotes
UPDATE THE_LOTES SET SELECTTED = 'D'
WHERE IDARCHIVOINTERCAMBIO IN (SELECT DISTINCT IDARCHIVOINTERCAMBIO FROM THE_VIAJES_CARGA)
  AND SELECTTED IS NULL;
--281285
