
TRUNCATE TABLE THE_VIAJES_MUESTRA;

CREATE TABLE THE_VIAJES_MUESTRA
(
  CODIGOLINEA           NUMERIC,
  RAMAL                 CHARACTER VARYING(5),
  NROTARJETAEXTERNO     CHARACTER VARYING(16),
  CODIGOTRXTARJETA      NUMERIC,
  FECHATRX              DATE,
  FECHAINGRESO          DATE,
  IDARCHIVOINTERCAMBIO  INT,
  FILE_ID               NUMERIC,
  C_CONTROL_POINT1      NUMERIC,
  C_CONTROL_POINT2      NUMERIC,
  PORC_RECORRIDO        NUMERIC
);

DROP TABLE THE_VIAJESMAYO;

CREATE TABLE THE_VIAJESMAYO
(
  CODIGOLINEA           NUMERIC,
  RAMAL                 CHARACTER VARYING(5),
  NROTARJETAEXTERNO     CHARACTER VARYING(16),
  CODIGOTRXTARJETA      NUMERIC,
  FECHATRX              TIMESTAMP,
  FECHAINGRESO          TIMESTAMP,
  IDARCHIVOINTERCAMBIO  INT,
  FILE_ID               NUMERIC,
  C_CONTROL_POINT1      NUMERIC,
  C_CONTROL_POINT2      NUMERIC,
  PORC_RECORRIDO        NUMERIC,
  LATITUDPTO3						NUMERIC,
  LONGITUDPTO3 					NUMERIC,
  DISTANCIA 						NUMERIC
);

CREATE TABLE THE_VIAJES_CARGA
(
  CODIGOLINEA           NUMERIC,
  RAMAL                 CHARACTER VARYING(5),
  NROTARJETAEXTERNO     CHARACTER VARYING(16),
  CODIGOTRXTARJETA      NUMERIC,
  FECHATRX              TIMESTAMP,
  FECHAINGRESO          TIMESTAMP,
  IDARCHIVOINTERCAMBIO  INT,
  FILE_ID               NUMERIC,
  C_CONTROL_POINT1      NUMERIC,
  C_CONTROL_POINT2      NUMERIC,
  PORC_RECORRIDO        NUMERIC,
  LATITUDPTO3						NUMERIC,
  LONGITUDPTO3 					NUMERIC,
  DISTANCIA 						NUMERIC
);

ALTER TABLE THE_VIAJES_MUESTRA 
ADD	latitudpto3 NUMERIC,
ADD  longitudpto3 NUMERIC,
ADD  distancia NUMERIC;


SET datestyle = "ISO, DMY";

COPY THE_VIAJES_MUESTRA FROM 'E:\pruebas\THE_VIAJES.CSV' CSV  DELIMITER ';'  HEADER;

COPY THE_VIAJES_MUESTRA FROM 'E:\pruebas\THE_VIAJES145.CSV' CSV  DELIMITER ';'  HEADER;

COPY THE_VIAJES_MUESTRA FROM 'E:\pruebas\THE_VIAJESvarios1.CSV' CSV  DELIMITER ';'  HEADER;

COPY THE_VIAJESMAYO FROM 'E:\pruebas\THE_VIAJES20150501inicial.CSV' CSV  DELIMITER ';'  HEADER;

COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150501.CSV' CSV  DELIMITER ';'  HEADER; -- ya esta totalmente cargado en el THE_VIAJES20150501inicial.csv NO CARGAR
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150502.CSV' CSV  DELIMITER ';'  HEADER;
delete from THE_VIAJES_carga where fechatrx < to_timestamp('20150502 03:00:00', 'YYYYMMDD HH24:MI:SS'); -- se eliminan los registros ya cargados en THE_VIAJES20150501inicial del dia 2
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150503.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150504.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150505.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150506.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150507.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150508.CSV' CSV  DELIMITER ';'  HEADER;
COPY THE_VIAJES_CARGA FROM 'E:\pruebas\THE_VIAJES20150509.CSV' CSV  DELIMITER ';'  HEADER;


CREATE INDEX THE_VIAJES_IDX ON THE_VIAJES_MUESTRA (CODIGOLINEA, RAMAL);

/*consulta para actualizar la proyeccion a la ruta*/

SELECT * FROM THE_VIAJES_MUESTRA WHERE PORC_RECORRIDO IS NULL;

SELECT distinct codigolinea FROM THE_VIAJES;
;




UPDATE THE_VIAJES_MUESTRA
SET DISTANCIA = NULL
WHERE DISTANCIA = 0;

UPDATE THE_VIAJES_MUESTRA a
SET latitudpto3 = b.latitudpto3,
longitudpto3 = b.longitudpto3,
distancia = b.distancia
FROM proyeccionruta b
where a.nrotarjetaexterno = b.nrotarjetaexterno
  and a.codigotrxtarjeta = b.codigotrxtarjeta;


SELECT COUNT(*) FROM THE_VIAJES_MUESTRA WHERE distancia IS not  NULL;

/*consulta para obtener las rutas*/
SELECT B.NROTARJETAEXTERNO, A.LONGITUD longitudpto1, A.LATITUD latitudpto1, C.LONGITUD longitudpto2, C.LATITUD latitudpto2, B.PORC_RECORRIDO
    FROM  PTOCONTROL201505 A, THE_VIAJES_MUESTRA B, PTOCONTROL201505 C 
    WHERE A.FILE_ID = B.FILE_ID
      AND A.C_CONTROL_POINT = B.C_CONTROL_POINT1 
      AND B.FILE_ID = C.FILE_ID
      AND B.C_CONTROL_POINT2 = C.C_CONTROL_POINT
      AND (PORC_RECORRIDO < 0.1 OR PORC_RECORRIDO > 0.9)
      AND B.CODIGOLINEA = 680
      AND B.RAMAL = '3145'
    ORDER BY B.FECHATRX;

RENAME TABLE THE_VIAJES THE_VIAJES_MUESTRA;

/*PARA VIAJES MAYO*/               

ALTER TABLE THE_VIAJESMAYO 
ADD	paradaorigen NUMERIC,
ADD  paradadestin NUMERIC;

ALTER TABLE THE_VIAJESMAYO 
ADD sentido character varying(2);

ALTER TABLE THE_VIAJESMAYO 
ADD	procesado CHARACTER VARYING(5);

CREATE INDEX THE_VIAJESMAYO_TRJ_IDX ON THE_VIAJESMAYO (NROTARJETAEXTERNO);

CREATE INDEX THE_VIAJESMAYO_TRJ_IDX2 ON THE_VIAJESMAYO (file_id);

CREATE INDEX THE_VIAJESMAYO_IDX2 ON THE_VIAJESMAYO (CODIGOLINEA, RAMAL);

CREATE INDEX DIST_PARADAS_IDX1 ON DIST_PARADAS (LINEA_ORIGEN, RAMAL_ORIGEN, SENTIDO_ORIGEN, PARADA_ORIGEN);


ALTER TABLE THE_VIAJESMAYO
ADD c_control_point_dest INTEGER,
ADD fecha_dest TIMESTAMP;

SELECT (fecha_dest - fechatrx) FROM THE_VIAJESMAYO WHERE FECHA_DEST IS NOT NULL;

SELECT AVG((fecha_dest - fechatrx)),COUNT(*)
FROM THE_VIAJESMAYO 
WHERE C_CONTROL_POINT_DEST IS NOT NULL
  AND (fecha_dest - fechatrx) > INTERVAL '1 DAY';

   
SELECT FECHATRX, FECHA_DEST, extract(epoch from fecha_dest - fechatrx), (fecha_dest - fechatrx), 
c_control_point2 - c_control_point_dest dif, *
FROM THE_VIAJESMAYO 
WHERE C_CONTROL_POINT_DEST IS NOT NULL
  AND (fecha_dest - fechatrx) < INTERVAL ' MINUTE'
ORDER BY dif;

SELECT *
FROM THE_VIAJESMAYO 
WHERE C_CONTROL_POINT_DEST IS NOT NULL
  AND (fecha_dest - fechatrx) < INTERVAL '2 MINUTE';

SELECT fechatrx, fecha_dest, fechatrx - fecha_dest, * 
FROM THE_VIAJESMAYO
WHERE NROTARJETAEXTERNO = '1800407782'
ORDER BY CODIGOTRXTARJETA;

SELECT * FROM PARADAS
WHERE LINEA = '35' AND RAMAL = '49' AND SENTIDO = 'V';

SELECT * FROM DIST_PARADAS WHERE LINEA_ORIGEN = '154' AND RAMAL_ORIGEN = '353' AND SENTIDO_ORIGEN = 'V' AND PARADA_ORIGEN = 21 AND LINEA_DESTINO = '35' AND RAMAL_DESTINO = '49' AND SENTIDO_DESTINO = 'I';
;

SELECT CAST(TO_DATE('20000101','YYYYMMDD') AS TIMESTAMP WITH TIME zone) + SEGUNDOSPTO * INTERVAL '1 SECOND', * 
FROM PTOCONTROL201505B 
WHERE FILE_ID = 38724368;

