
ALTER TABLE PARADAS
ADD departamento character varying(50),
ADD barrio character varying(50) ;

SELECT * FROM PARADAS_COMPLEMENTO;

SELECT * FROM PARADAS;

UPDATE paradas A
SET DEPARTAMENTO = B.DEPARTAMENTO, BARRIO = B.BARRIO
FROM PARADAS_COMPLEMENTO B
WHERE A.LINEA = B.LINEA 
  AND A.RAMAL = B.RAMAL
  AND A.SENTIDO = B.SENTIDO
  AND A.CLUSTERORD = B.CLUSTERORD;
  

