/*INVENTARIO DE TABLAS DENTRO DEL REDSHIFT

LINEASRAMALTRX 1093 REGISTROS TABLA que contiene una lista de linea - ramales de colectivos

PUNTOSCONTROL 7.698.264 PARA 1092 linea / ramales. Contiene 10.000 puntos de control para cada linea / ramal.
Esta tabla vendría a ser algo asi como la tabla de los viajes que contiene tanto informacion de los viajes como delGPS de los puntos de control
La desventaja de esta tabla es que los putnos de control que no tengan usos, no van a aparecer, es por eso que se hizo la siguiente tabla

RAWPUNTOSCONTROL  

*/


/***** LINEASRAMALTRX **************/
/* TABLA que contiene una lista de linea - ramales de colectivos*/
DROP TABLE LINEASRAMALTRX;

SELECT * FROM LINEASRAMALTRX LIMIT 10;

CREATE TABLE  LINEASRAMALTRX AS
SELECT LINEA.CODIGOLINEA LINEA, CODIGOTRAYECTO RAMAL, LINEA.DESCRIPCION,MT.CODIGOLINEA, AREAGEOGRAFICA, COUNT(*) CANTIDADTRX
FROM MOVIMIENTOTARJETA2 MT, LINEA
WHERE LINEA.IDLINEA = MT.CODIGOLINEA
  AND CODIGOTIPOTRX = 19
  AND AREAGEOGRAFICA IN (1,12,13)
GROUP BY LINEA.CODIGOLINEA, CODIGOTRAYECTO, LINEA.DESCRIPCION, MT.CODIGOLINEA, AREAGEOGRAFICA

1093

SELECT CODIGOLINEA, RAMAL, COUNT(*)
FROM LINEASRAMALTRX
GROUP BY CODIGOLINEA, RAMAL
HAVING COUNT(*) > 1
ORDER BY CODIGOLINEA, RAMAL
--NO hay ningun codigolinea ramal repetido


/*******************************************************************************/
/********* consultas para armar la tabla PUNTOSCONTROL    **********************/
/*******************************************************************************/


/*esta sentencia se utilizó en test.py para cargar 10.000 punto de uso por cada linea ramal*/
INSERT INTO PUNTOSCONTROL (CODIGOLINEA, RAMAL, NROTARJETAEXTERNO, TIPOMAPPING, CODIGOTRXTARJETA, FECHATRX, FECHAINGRESO, IDARCHIVOINTERCAMBIO, 
														REF_EXT, CONTROL_POINT_1, LONGITUDPTO1, LATITUDPTO1, FECHAPTO1)             
	SELECT LINEA.CODIGOLINEA CODIGOLINEA, MT.CODIGOTRAYECTO RAMAL, MT.NROTARJETAEXTERNO, MT.TIPOMAPPING, MT.CODIGOTRXTARJETA, MT.FECHATRX, MT.FECHAINGRESO, MT.IDARCHIVOINTERCAMBIO
						L.REF_EXT, P.C_CONTROL_POINT CONTROL_POINT_1, P.LONGITUD LONGITUDPTO1, P.LATITUD LATITUDPTO1, P.DATE_TIME FECHAPTO1
	FROM MOVIMIENTOTARJETA2 MT,
	     LOTE L, 
	     POSITIONING P
	WHERE MT.IDARCHIVOINTERCAMBIO = L.ID_LOTE
	  AND CODIGOTIPOTRX = 19
		AND L.REF_EXT = P.FILE_ID
	  AND MT.ID_POSICIONAMIENTO = P.C_CONTROL_POINT
		AND MT.CODIGOLINEA = linea
		AND MT.CODIGOTRAYECTO = ramal
		LIMIT 10000; 

UPDATE PUNTOSCONTROL
SET CONTROL_POINT_2 = P2.C_CONTROL_POINT,
	  LONGITUDPTO2 = P2.LONGITUD,
	  LATITUDPTO2 = P2.LATITUD,
	  FECHATPTO2 = P2.DATE_TIME
FROM POSITIONING P2
WHERE REF_EXT = P2.FILE_ID
  AND CONTROL_POINT_1 + 1 = P2.C_CONTROL_POINT  

UPDATE PUNTOSCONTROL
SET PORC_RECORRIDO = EXTRACT(SECOND FROM FECHATRX - FECHAPTO1) / EXTRACT(SECOND FROM FECHATPTO2 - FECHAPTO1)
WHERE EXTRACT(SECOND FROM FECHATPTO2 - FECHAPTO1) > 0;

UPDATE PUNTOSCONTROL
SET LINEA = A.LINEA 
FROM LINEASRAMALTRX A
WHERE PUNTOSCONTROL.CODIGOLINEA = A.CODIGOLINEA
  AND PUNTOSCONTROL.RAMAL = A.RAMAL


SELECT * FROM PUNTOSCONTROL WHERE LINEA = 118
 
SELECT * FROM PUNTOSCONTROL WHERE LINEA = 118  ORDER BY IDARCHIVOINTERCAMBIO, FECHATRX  LIMIT 1000


SELECT COUNT(*) FROM LINEASRAMALTRX

SELECT COUNT(*) FROM (
SELECT CODIGOLINEA, RAMAL, COUNT(*)
FROM PUNTOSCONTROL 
GROUP BY CODIGOLINEA, RAMAL
)
--1092

SELECT COUNT(*)  FROM PUNTOSCONTROL 
--7698264

SELECT COUNT(*)  FROM PUNTOSCONTROL WHERE PORC_RECORRIDO IS NULL;
--100


SELECT * FROM PUNTOSCONTROL WHERE CODIGOLINEA = '159' LIMIT 100;

SELECT * FROM LINEASRAMALTRX WHERE LINEA = '118';


/*******************************************************************************/
/********* consultas para armar la tabla RAWPUNTOSCONTROL    **********************/
/*******************************************************************************/

--vamos a hacer una tabla que contenga todos los puntos de control de varios UD de la linea 118
--la idea es cargar todos los puntos de control de una linea en un día determinado

SELECT * FROM LINEASRAMALTRX WHERE LINEA = 118;

SELECT DISTINCT RAMAL FROM PUNTOSCONTROL WHERE CODIGOLINEA = 159 ;

--recuepro todos los file_id de 1 de agosto para la linea 118

		
DROP TABLE RAWPTOCONTROL;

DROP TABLE LOTES;

SELECT count(*)
FROM movimientotarjeta2 A, LOTE B
WHERE FECHATRX > TO_DATE('20140802','YYYYMMDD') AND FECHATRX < TO_DATE('20140803','YYYYMMDD')
  AND A.idarchivointercambio = B.id_lote;

DROP TABLE LOTES;

CREATE TABLE LOTES AS
SELECT B.ID_LOTE, REF_EXT FILE_ID, C.LINEA, C.RAMAL, MIN(FECHATRX) MINFECHATRX, MAX(FECHATRX) MAXFECHATRX
FROM movimientotarjeta2 A, LOTE B, LINEASRAMALTRX C
WHERE FECHATRX > TO_DATE('20140802','YYYYMMDD') AND FECHATRX < TO_DATE('20140803','YYYYMMDD')
  AND A.CODIGOLINEA = C.CODIGOLINEA 
  AND A.CODIGOTRAYECTO = C.RAMAL
  AND C.LINEA IN ('158', '12', '111', '68', '152', '160', '64', '85', '92', '28', '57') 
  AND C.RAMAL IN (196, 63, 186, 		200,   118,   263,   340,  213,  301,  443, 391)
  AND A.idarchivointercambio = B.id_lote
GROUP BY B.ID_LOTE, REF_EXT, C.LINEA, C.RAMAL;

--Controles
SELECT LINEA, RAMAL, COUNT(*) cantidad_lotes FROM LOTES GROUP BY LINEA, RAMAL ORDER BY LINEA, RAMAL  ;

SELECT COUNT(*) FROM LOTES;
--928 lotes total


DROP TABLE RAWPTOCONTROL;

CREATE TABLE RAWPTOCONTROL AS
SELECT B.LINEA, 
			 B.RAMAL, 
			 P.FILE_ID, 
			 C_CONTROL_POINT, 
			 LONGITUD, 
			 LATITUD, 
			 DATE_TIME FECHAPTO1
FROM POSITIONING P, LOTES B
WHERE P.FILE_ID = B.FILE_ID
ORDER BY FILE_ID, C_CONTROL_POINT;

DROP TABLE RAWPTOCONTROL2;

CREATE TABLE RAWPTOCONTROL2 AS  
SELECT linea, 
	   ramal, 
	   file_id, 
	   c_control_point, 
	   longitud, 
	   latitud, 
	   fechapto1, 
	   NULL estado , 	
	   (case when LAG(file_id, 1) OVER(ORDER BY FILE_ID, C_CONTROL_POINT )= file_id  then EXTRACT(SEC FROM FECHAPTO1 - LAG(FECHAPTO1,1) OVER(ORDER BY FILE_ID, C_CONTROL_POINT )) end) DIFSEC
FROM RAWPTOCONTROL A 
ORDER BY FILE_ID, C_CONTROL_POINT;

UPDATE RAWPTOCONTROL2
SET ESTADO = CASE WHEN DIFSEC > 235 AND DIFSEC < 245 THEN 'S' ELSE 'N' END;


SELECT COUNT(*) FROM RAWPTOCONTROL2;

SELECT * FROM RAWPTOCONTROL2 ORDER BY FILE_ID, C_CONTROL_POINT limit 100; 



--cantidad de turnos realizados
SELECT COUNT(DISTINCT FILE_ID) FROM RAWPTOCONTROL;
--82

--cantidad de puntos de control por cada turno realizado
SELECT FILE_ID, COUNT(*) CANTIDAD FROM RAWPTOCONTROL GROUP BY FILE_ID;

--promedio
SELECT FILE_ID, COUNT(*) CANTIDAD FROM RAWPTOCONTROL GROUP BY FILE_ID;
