drop table PTOSCONTROL;

CREATE TABLE PTOSCONTROL AS
SELECT DISTINCT CAST(linea AS INTEGER) LINEA, CAST(ramal AS INTEGER) RAMAL, IDARCHIVOINTERCAMBIO, CAST(CONTROL_POINT_1 AS INTEGER) CONTROL_POINT_1,
			 CAST(longitudpto1 AS FLOAT) longitudpto1,  CAST(latitudpto1 AS FLOAT) latitudpto1, 
			strftime('%Y-%m-%d %H:%M:%S', fechapto1) fechapto1
FROM secuencia 

SELECT LINEA, RAMAL, IDARCHIVOINTERCAMBIO, CONTROL_POINT_1, LONGITUDPTO1, LATITUDPTO1, FECHAPTO1 FROM PTOSCONTROL ORDER BY CONTROL_POINT_1;

SELECT * FROM RAWPTOCONTROL LIMIT 100;

SELECT * FROM RAWPTOCONTROL2 LIMIT 100;


DROP TABLE RAWPTOCONTROL2;


CREATE TABLE RAWPTOCONTROL2 AS 
SELECT CAST(LINEA AS INTEGER) linea, 
				CAST(RAMAL AS INTEGER) ramal, 
			 CAST(FILE_ID AS INTEGER) file_id,
		   CAST(C_CONTROL_POINT AS INTEGER) c_control_point, 
		   CAST(LONGITUD AS FLOAT) longitud,
		   CAST(LATITUD AS FLOAT) latitud,
		   FECHAPTO1 fechapto,
		   CAST(strftime('%s', fechapto1) AS REAL) segundospto,
		   ESTADO
FROM RAWPTOCONTROL;

commit;

SELECT COUNT(*) FROM RAWPTOCONTROL2;

SELECT * FROM SENTIDO ORDER BY FILE_ID, C_CONTROL_POINT;

SELECT LINEA, RAMAL, FILE_ID, COUNT(*)
FROM SENTIDO 
WHERE SUBSTR(FECHAPTO, 9,2) = '02'
AND SUBSTR(FECHAPTO, 12,2) IN ('07','08','09','10','11','12','13','14','15','16','17','18','19','20')
AND LINEA = 152
GROUP BY LINEA, RAMAL, FILE_ID
ORDER BY COUNT(*) DESC;

SELECT SUBSTR(FECHAPTO, 9,2), SUBSTR(FECHAPTO, 12,2), FECHAPTO FROM SENTIDO LIMIT 1000;

SELECT LINEA, FILE_ID, LONGITUD, LATITUD, FECHAPTO, SENTIDO FROM SENTIDO 
WHERE SUBSTR(FECHAPTO, 9,2) = '02'
AND SUBSTR(FECHAPTO, 12,2) IN ('07','08','09','10','11','12','13','14','15','16','17','18','19','20')
AND LINEA NOT IN (57)
AND LONGITUD <> 0 
and latitud <> 0
AND FILE_ID IN (
23017992,
22845119,
22841075
		);


/***************************************************************************************/
/******************* ANALISIS DE LOS RESULTADOS (PUNTA 4/3/2015 ) **********************/

SELECT COUNT(*) FROM RAWPTOCONTROL2; --366.526

SELECT COUNT(*) FROM RAWPTOCONTROL2 WHERE ESTADO = 'S'; -- 169988

SELECT LINEA, ESTADO, COUNT(*) FROM RAWPTOCONTROL2 GROUP BY LINEA, ESTADO ORDER BY LINEA, ESTADO; -- 169988

DROP TABLE ANALISIS;

CREATE TABLE ANALISIS AS
SELECT A.LINEA, A.RAMAL, A.FILE_ID, A.C_CONTROL_POINT, 
			 (CASE WHEN A.LATITUD = 0 THEN 'N' ELSE 'S' END) ESTADOCOOR, 
			 A.ESTADO,
			 SENTIDO  
FROM RAWPTOCONTROL2 A LEFT OUTER JOIN  SENTIDO B 
ON B.FILE_ID = A.FILE_ID 
AND A.C_CONTROL_POINT = B.C_CONTROL_POINT;

SELECT * FROM ANALISIS LIMIT 100;


SELECT LINEA Linea, RAMAL Ramal,
			 COUNT(*)  "Lotes procesados",
			 SUM(CANTIDAD) "PC procesados",			 
			 SUM(MALASTIEMPO) "PC malos por tiempo",
			 SUM(MALASCOOR) "PC long vacio" ,
			 SUM(BUENESTADO) "PC buen estado",
			 SUM(CANTIDA) "Cantidad Ida",
			 SUM(CANTVUELTA) "Cantidad Vuelta"
FROM 
(
SELECT LINEA, RAMAL, FILE_ID, 
			SUM(CASE WHEN ESTADO = 'S' THEN 0 ELSE 1 END) MALASTIEMPO,
			SUM(CASE WHEN ESTADOCOOR = 'S' THEN 0 ELSE 1 END) MALASCOOR,
			SUM(CASE WHEN ESTADO = 'S' AND ESTADOCOOR = 'S' THEN 1 ELSE 0 END) BUENESTADO,
			SUM(CASE WHEN ESTADO = 'S' AND ESTADOCOOR = 'S' and SENTIDO = 'I' THEN 1 ELSE 0 END) CANTIDA,
			SUM(CASE WHEN ESTADO = 'S' AND ESTADOCOOR = 'S' and SENTIDO = 'V' THEN 1 ELSE 0 END) CANTVUELTA,			
			COUNT(*) CANTIDAD
FROM ANALISIS
GROUP BY LINEA, RAMAL, FILE_ID
)
GROUP BY LINEA,RAMAL;







