CREATE TABLE MOVIMIENTOTARJETA2
(CODIGOTRXTERMINAL INTEGER,
MONTO  varchar(20),
SALDO  varchar(20),
CANTTRX INTEGER,
CODIGOROL VARCHAR(20),
CODIGOERROR INTEGER,
CODIGOTIPOTRX INTEGER,
CODIGOENTIDAD INTEGER,
CODIGOTIPOTARJETA INTEGER,
CODIGOTERMINAL INTEGER,
CODIGOSITIO INTEGER,
NROTARJETA int8,
FECHATRX DATE,
CODIGOTIPOTECNOLOGIA INTEGER,
CODIGOCONTRATO INTEGER,
CODIGOTRXTARJETA INTEGER,
CODIGOLINEA INTEGER,
ENTIDADFINANCIERA INTEGER,
FECHAINGRESO DATE,
IDARCHIVOINTERCAMBIO INTEGER,
IDINCONSISTENCIA VARCHAR(20),
MONEDERO_ID INTEGER,
EMISOR_CONTRATO INTEGER,
NROTARJETAEXTERNO INTEGER,
SAM_ID VARCHAR(30),
LG_ID VARCHAR(50),
TIPO_TERMINAL INTEGER,
ACCION_HL INTEGER,
ID_COMBINACION INTEGER,
ID_REGLA_COMBINACION INTEGER,
VALOR_TARIFA varchar(20),
ID_SERVICIO INTEGER,
ENTIDAD_EMISORA_TARJ INTEGER,
VERSION_TIPO_TRX INTEGER,
TIPOMAPPING INTEGER,
ID_INTEGRADOR INTEGER,
CODIGOTRAYECTO INTEGER,
EMISOR_MONEDERO INTEGER,
CODIGOSUBTIPOTRX INTEGER,
SECCION_FIN INTEGER,
SECCION_INICIO INTEGER,
DESCUENTO varchar(20),
PROVISION varchar(20),
ID_POSICIONAMIENTO INTEGER,
PTC INTEGER,
LTC INTEGER,
CODIGOTIPOLINEA VARCHAR(30)
);

SHOW datestyle;
SET datestyle = "ISO, DMY";

SELECT TO_NUMBER('1', '9') FROM GUI_LOTES LIMIT 1;

COPY MOVIMIENTOTARJETA2 FROM 'C:\Users\GSIDONI\Desktop\DATA_ADATOPRD_MT20140901\DATA_ADATOPRD_MT20140901.CSV' CSV  DELIMITER ';'  HEADER;

commit;

SELECT COUNT(*) FROM MOVIMIENTOTARJETA2;

DROP TABLE  RAWPTOCONTROL;

CREATE TABLE RAWPTOCONTROL
(
  LINEA            VARCHAR(50),
  RAMAL            VARCHAR(5),
  FILE_ID          INTEGER                       NOT NULL,
  C_CONTROL_POINT  INTEGER,
  LONGITUD         NUMERIC(13,10) ,
  LATITUD          NUMERIC(13,10),
  FECHAPTO         DATE,
  ESTADO           CHAR(1),
  DIFSEC           REAL,
  SEGUNDOSPTO      REAL,
  FECHAINGRESO     DATE
);

CREATE TABLE RAWPTOCONTROL_TEMP
(
  LINEA            VARCHAR(50),
  RAMAL            VARCHAR(5),
  FILE_ID          INTEGER                       NOT NULL,
  C_CONTROL_POINT  INTEGER,
  LONGITUD         VARCHAR,
  LATITUD          VARCHAR,
  FECHAPTO         DATE,
  ESTADO           CHAR(1),
  DIFSEC           REAL,
  SEGUNDOSPTO      REAL,
  FECHAINGRESO     DATE
);

-- EN caso de que de error de acceso agregar al archivo el usuario everyone
COPY RAWPTOCONTROL_TEMP FROM 'E:\pruebas\RAWPTOCONTROL.CSV' CSV  DELIMITER ';'  HEADER;

CREATE TABLE RAWPTOCONTROL AS
SELECT   LINEA,  RAMAL,  FILE_ID,  C_CONTROL_POINT,  
				TO_NUMBER(replace(LONGITUD, ',', '.'), '99999.9999999') LONGITUD,
				TO_NUMBER(replace(LATITUD, ',', '.'), '99999.9999999') LATITUD,
			  FECHAPTO,  ESTADO,  DIFSEC,  SEGUNDOSPTO,  FECHAINGRESO
FROM RAWPTOCONTROL_TEMP;

DROP TABLE GUI_LOTES;

CREATE TABLE GUI_LOTES
(
  ID_LOTE  INTEGER,
  FILE_ID  INTEGER,
  LINEA    VARCHAR(50),
  RAMAL    VARCHAR(5),
  FECHAINGRESO DATE,
  PROCESADO VARCHAR(5)
);

CREATE INDEX GUI_LOTES_FILE_ID ON GUI_LOTES (FILE_ID);

COPY GUI_LOTES FROM 'E:\pruebas\GUI_LOTES.CSV' CSV  DELIMITER ';'  HEADER;

UPDATE GUI_LOTES SET PROCESADO = NULL WHERE PROCESADO IS NOT NULL;
COMMIT;

SELECT count(*) FROM GUI_LOTES WHERE PROCESADO IS NOT NULL;

SELECT * FROM "Sentido";

SELECT COUNT(*) FROM RAWPTOCONTROL;





